"""Tests for the PVD (Pixel Value Differencing) core.

Coverage:
  * Range-table lookup (bucket edges + fallback).
  * Bit helpers round-trip.
  * Encode -> decode round-trip across all direction x range-table combos.
  * Bit-for-bit parity with the JS reference in ``index.html`` via a
    golden-vector fixture (``fixtures/pvd/js_reference.json``).
  * Capacity honesty and overflow rejection.
  * Wrong config on decode fails cleanly instead of returning garbage.
  * Uniform-carrier edge case (diff = 0 everywhere).
  * PIL mode conversion (RGBA / L are accepted).

The fixture was generated by ``scratchpad/pvd_js_ref.mjs``, which is a
verbatim copy of the JS ``pvdEncode`` / ``pvdDecode`` block. If the JS
side ever changes, regenerate the fixture and check the diff.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from PIL import Image

import steg_core
from steg_core import PVD_RANGES, find_pvd_range

FIXTURE = Path(__file__).parent / "fixtures" / "pvd" / "js_reference.json"

DIRECTIONS = ["horizontal", "vertical", "both"]
RANGE_TYPES = ["wu-tsai", "wide", "narrow"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _noisy_carrier(size: int, seed: int) -> Image.Image:
    rng = np.random.default_rng(seed)
    arr = rng.integers(0, 256, size=(size, size, 3), dtype=np.uint8)
    return Image.fromarray(arr, mode="RGB")


# ---------------------------------------------------------------------------
# Range-table lookup
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("range_type", RANGE_TYPES)
def test_find_range_covers_every_bucket_edge(range_type):
    ranges = PVD_RANGES[range_type]
    for r in ranges:
        assert find_pvd_range(r.lower, ranges) is r
        assert find_pvd_range(r.upper, ranges) is r
        # Negative diffs use |diff|.
        assert find_pvd_range(-r.lower, ranges) is r
        assert find_pvd_range(-r.upper, ranges) is r


def test_find_range_falls_back_to_last_bucket_when_out_of_domain():
    # Should never happen for valid u8 diffs, but the JS side falls back.
    ranges = PVD_RANGES["wu-tsai"]
    assert find_pvd_range(9999, ranges) is ranges[-1]


# ---------------------------------------------------------------------------
# Round-trip sweep
# ---------------------------------------------------------------------------

ROUNDTRIP_PAYLOADS = [
    b"x",
    b"hello PVD",
    b"The quick brown fox jumps over the lazy dog." * 3,
]


@pytest.mark.parametrize("direction", DIRECTIONS)
@pytest.mark.parametrize("range_type", RANGE_TYPES)
@pytest.mark.parametrize("payload", ROUNDTRIP_PAYLOADS)
def test_roundtrip(direction, range_type, payload):
    carrier = _noisy_carrier(64, seed=42)
    stego = steg_core.pvd_encode(carrier, payload, direction=direction, range_type=range_type)
    out = steg_core.pvd_decode(stego, direction=direction, range_type=range_type)
    assert out == payload


# ---------------------------------------------------------------------------
# JS parity: golden vectors
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def js_reference():
    if not FIXTURE.exists():
        pytest.skip(f"JS reference fixture missing: {FIXTURE}")
    return json.loads(FIXTURE.read_text())


@pytest.fixture(scope="module")
def js_carrier(js_reference):
    w, h = js_reference["width"], js_reference["height"]
    rgb = np.frombuffer(bytes.fromhex(js_reference["src_rgb_hex"]), dtype=np.uint8)
    return Image.fromarray(rgb.reshape(h, w, 3), mode="RGB")


@pytest.mark.parametrize("direction", DIRECTIONS)
@pytest.mark.parametrize("range_type", RANGE_TYPES)
def test_encoded_bytes_match_js_reference(direction, range_type, js_reference, js_carrier):
    payload = bytes.fromhex(js_reference["payload_hex"])
    case = js_reference["cases"][f"{direction}::{range_type}"]

    stego = steg_core.pvd_encode(js_carrier, payload, direction=direction, range_type=range_type)
    py_hex = np.asarray(stego, dtype=np.uint8).tobytes().hex()
    assert py_hex == case["encoded_hex"], (
        f"Python encoded bytes diverge from JS reference for {direction}/{range_type}."
    )


@pytest.mark.parametrize("direction", DIRECTIONS)
@pytest.mark.parametrize("range_type", RANGE_TYPES)
def test_decode_matches_js_payload(direction, range_type, js_reference, js_carrier):
    payload = bytes.fromhex(js_reference["payload_hex"])
    stego = steg_core.pvd_encode(js_carrier, payload, direction=direction, range_type=range_type)
    decoded = steg_core.pvd_decode(stego, direction=direction, range_type=range_type)
    assert decoded == payload


# ---------------------------------------------------------------------------
# Capacity + overflow
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("direction", DIRECTIONS)
@pytest.mark.parametrize("range_type", RANGE_TYPES)
def test_capacity_is_honest_lower_bound(direction, range_type):
    carrier = _noisy_carrier(48, seed=7)
    cap = steg_core.pvd_capacity_bytes(carrier, direction=direction, range_type=range_type)
    # Half the natural capacity should always fit; embedding shifts diffs
    # around but not enough to invalidate a payload this small.
    payload = b"P" * (cap // 2)
    stego = steg_core.pvd_encode(carrier, payload, direction=direction, range_type=range_type)
    assert steg_core.pvd_decode(stego, direction=direction, range_type=range_type) == payload


def test_both_direction_capacity_is_max_not_sum():
    """`both` mode is limited by the horizontal-only cap (see module docstring).

    Reporting the sum would lie to callers -- horizontal edits mutate
    pixels the vertical pass then reads, so payloads that spill into
    the vertical pass corrupt on decode.
    """
    carrier = _noisy_carrier(48, seed=7)
    h = steg_core.pvd_capacity_bytes(carrier, direction="horizontal")
    v = steg_core.pvd_capacity_bytes(carrier, direction="vertical")
    both = steg_core.pvd_capacity_bytes(carrier, direction="both")
    assert both == max(h, v)


def test_both_direction_fails_on_spillover_payload():
    """Payloads larger than horizontal-only capacity cannot round-trip in ``both``.

    Documents the inherited-from-JS limitation so any future refactor
    that "fixes" it has to update this test consciously.
    """
    carrier = _noisy_carrier(48, seed=7)
    h_cap = steg_core.pvd_capacity_bytes(carrier, direction="horizontal")
    payload = b"X" * (h_cap + 100)  # forces spill into vertical pass
    stego = steg_core.pvd_encode(carrier, payload, direction="both")
    with pytest.raises(ValueError):
        steg_core.pvd_decode(stego, direction="both")


def test_payload_too_large_raises_value_error():
    # Tiny 4x4 carrier -- capacity is only a few bytes.
    carrier = _noisy_carrier(4, seed=1)
    huge = b"Q" * 10_000
    with pytest.raises(ValueError, match="payload does not fit"):
        steg_core.pvd_encode(carrier, huge, direction="horizontal", range_type="wu-tsai")


def test_encode_rejects_unknown_range_type():
    carrier = _noisy_carrier(16, seed=1)
    with pytest.raises(ValueError, match="unknown range_type"):
        steg_core.pvd_encode(carrier, b"hi", range_type="not-a-real-table")


def test_decode_rejects_unknown_direction():
    carrier = _noisy_carrier(16, seed=1)
    stego = steg_core.pvd_encode(carrier, b"hi")
    with pytest.raises(ValueError, match="unknown direction"):
        steg_core.pvd_decode(stego, direction="diagonal")


# ---------------------------------------------------------------------------
# Wrong-config decoding fails loudly
# ---------------------------------------------------------------------------

def test_wrong_range_type_on_decode_fails_or_returns_wrong_bytes():
    """Decoding with the wrong range table must not silently return the payload.

    Either raises (length header parsed as absurd) or returns a byte
    string that isn't equal to the payload. Both are acceptable -- the
    property we care about is 'not a false positive'.
    """
    carrier = _noisy_carrier(64, seed=99)
    payload = b"exact-bytes-please"
    stego = steg_core.pvd_encode(carrier, payload, range_type="wu-tsai")
    try:
        out = steg_core.pvd_decode(stego, range_type="wide")
    except ValueError:
        return  # Loud failure, ideal.
    assert out != payload


def test_wrong_direction_on_decode_fails_or_returns_wrong_bytes():
    carrier = _noisy_carrier(64, seed=99)
    payload = b"exact-bytes-please"
    stego = steg_core.pvd_encode(carrier, payload, direction="horizontal")
    try:
        out = steg_core.pvd_decode(stego, direction="vertical")
    except ValueError:
        return
    assert out != payload


# ---------------------------------------------------------------------------
# Miscellaneous
# ---------------------------------------------------------------------------

def test_decode_is_idempotent():
    carrier = _noisy_carrier(64, seed=5)
    payload = b"read me twice"
    stego = steg_core.pvd_encode(carrier, payload)
    a = steg_core.pvd_decode(stego)
    b = steg_core.pvd_decode(stego)
    assert a == b == payload


def test_solid_color_carrier_roundtrips():
    """Uniform gray image -- every pair starts with diff = 0.

    Exercises the 'shift both pixels to stay in [0,255]' branch because
    small non-zero diffs plant new pixels close to the extremes when the
    input is 0 or 255. A mid-gray keeps everyone honest.
    """
    arr = np.full((32, 32, 3), 128, dtype=np.uint8)
    carrier = Image.fromarray(arr, mode="RGB")
    payload = b"flat carrier"
    stego = steg_core.pvd_encode(carrier, payload)
    assert steg_core.pvd_decode(stego) == payload


def test_rgba_input_is_accepted():
    arr = np.zeros((32, 32, 4), dtype=np.uint8)
    arr[..., :3] = 100
    arr[..., 3] = 255
    carrier = Image.fromarray(arr, mode="RGBA")
    payload = b"alpha carrier"
    stego = steg_core.pvd_encode(carrier, payload)
    assert stego.mode == "RGB"
    assert steg_core.pvd_decode(stego) == payload


def test_grayscale_input_is_accepted():
    arr = np.full((32, 32), 90, dtype=np.uint8)
    carrier = Image.fromarray(arr, mode="L")
    payload = b"gray"
    stego = steg_core.pvd_encode(carrier, payload)
    assert steg_core.pvd_decode(stego) == payload
